### ISSUE TITLE
Tracking: Ganglion Backend Integration

### ISSUE THREAD

**Issue by aj-ptw** [OpenBCI/OpenBCI_GUI#34]
### New Features
- [ ] Building ganglion code as a binary. See [`electron`](http://electron.atom.io)
- [ ] Launching binary from processing. See processing's [`launch()`](https://processing.org/reference/launch_.html)
- [ ] Node process status checks
- [ ] Impedance checking
- [ ] Show no ganglion's found message in control panel
- [ ] Pass channel changing messages to node

### Bug Fixes
- [ ] Going back to the control panel should disconnect the Ganglion BLE inside the node process, but not stop the node process.
- [ ] FFT widget only goes to 100Hz max
