### ISSUE TITLE
Tracking: Ganglion Frontend

### ISSUE THREAD

**Issue by aj-ptw** [OpenBCI/OpenBCI_GUI#53]
### Bug Fixes
- [ ] FFT widget only goes to 100Hz max
- [ ] Cannot change the file name for a new output file. (can't type in text box)

### New features
- [ ] Impedance check button
- [ ] No ganglion found error message
